### ISSUE TITLE
Location info after parsing

### ISSUE THREAD

**Issue by emoon** [rotty/lexpr-rs#50]
Hi,

When a parse error happens an Optional location https://github.com/rotty/lexpr-rs/blob/master/lexpr/src/parse/error.rs#L27-L46 is included with the parse error which is great.

Something I have been thinking about is how to report errors after parsing (i.e when parsing is ok but some Symbol is incorrect) for example

```Lisp
((foo 1 2 3)
(bar 1 2 3))
```

So this data will parse just fine but say that I want to report that `bar` doesn't exist/is an invalid keyword I would like to report to the user where in the file the error is, but as the this data isn't available anymore after the parsing step I wonder what the suggested approach is to do this?

**Comment by rotty** [comment]
Thanks for the question! This is a missing feature; coincidentally, I've started using `lexpr` for implementing a DSL with S-expression syntax recently, and also noticed that this feature is lacking, and is essential to provide good error messages.

For implementing this, I'll have to do some research on how to extend the API to accommodate span information, probably looking at similar crates that already provide span information. If you have any suggestions, I'm all ears!

**Comment by emoon** [comment]
Yeah. My plan is to use `lexpr` for a configuration format something like this

```Lisp
(integer "MyInteger"
  (description "My nice integer")
  (value 0 -100 100))
```
So say that the user would write a typo of `description` like `descriptin` I want to be able to say something like this

```
filename:line:colum:
   (descriptin "My nice integer")
    ^
descriptin unknown type. Did you mean: description ?
```
I'm not sure what would work best in terms of spans and such. In my case having a `Location` for each Symbol/Type would likely be enough but having a span that say `start line:column - end line:column` would be more powerful for sure.

**Comment by rotty** [comment]
If giving spans is not terribly more difficult to implement, I'll be going for them, as they are, as you noted, strictly more powerful.

The `yaml-rust` binding has a low-level API that [allows obtaining markers](https://docs.rs/yaml-rust/0.4.3/yaml_rust/parser/trait.MarkedEventReceiver.html), which can then be turned into spans by a parser.

I' d envision something like a parser API addition that does not return a plain `Value`, but instead a type that keeps span information at each level. I don't think I want to add span information to `Value` itself, since (currently, at least) serde support works through `Value`, and for serde support, span information is not needed at the datum level; also adding span info to `Value` would be a hugely-breaking change.

**Comment by emoon** [comment]
I guess that will work. It likely will make the user code a bit more annoying as you need to loop over two things at the same time as you need to traverse them in the same way.

**Comment by rotty** [comment]
Another idea that *might* work, and would avoid the duplication, is to record span information the parser for each non-primitive value, using its address, and then add an API to retrieve the span information for a given value, if available. This would not work for `Value::Number`, `Value::Boolean`, `Value::Char`,`Value::Null` and `Value::Nil`, but it would avoid the duplication of the `Value` type (which indeed seems a bit gross).

**Comment by emoon** [comment]
I don't think that is good enough. It might be that some `Value::Number` is "invalid" (in terms of usage, not in terms of parsing) and then it should be able to report it. It also would make things inconsistent if not all `Value` types are supported imo.

Another thing that would be possible to do is to have an id on each Value. This might be as breaking as adding span info but if it isn't it would be possible to use this id to query the parser for span info.

**Comment by rotty** [comment]
> I don't think that is good enough. It might be that some `Value::Number` is "invalid" (in terms of usage, not in terms of parsing) and then it should be able to report it. It also would make things inconsistent if not all `Value` types are supported imo.
>
Jup, you have convinced me that this implementation is not desirable.

> Another thing that would be possible to do is to have an id on each Value. This might be as breaking as adding span info but if it isn't it would be possible to use this id to query the parser for span info.
>
I think it is just as much of a breaking change; `Value` is a public enum, so it cannot be changed at all without potentially breaking code using it. However, since there presumably are _very_ few users of `lexpr`, changing it is not totally out of the question. However, the `Value` type as-is is nice for using with `match`; including location information would make that less ergonomic for code that doesn't care about location information.

I have a possible solution in mind, which would retain `Value` as-is, and hopefully ends up reasonably ergonomic when destructuring data *including* location info. I'll update the issue when I have some PoC sketch in a WIP branch, and would appreciate your opinion on the approach.

**Comment by emoon** [comment]
Sounds good :)

**Comment by rotty** [comment]
@emoon FWIW, I now have pushed a PoC-level implementation to the `wip/location-info` branch, if you want to take a peek. To see some code adapted to the new API (but still not taking advantage of the location info), you can have a look at <https://gitlab.com/rotty/btm/-/tree/wip/location-info>. Be warned though, that the API is subject to change; however, I don't have any concrete changes in mind currently, besides fixes/additions. Also there are no API docs yet.

The main idea is to obtain a `Datum` via `Parser::parse_datum`, and then use `list_iter` and `vector_iter` to obtain references to inner values, including span information. For primitive values, the `Value` API can be used for destructuring.

A likely addition is adding convenience wrappers ala `read_str` and `read_str_custom`.

I suspect I will add work-alike variants of `list_iter` and `vector_iter` to `Value` in a future change. It turned out that `list_iter` allows for dealing with lists, including improper ones, quite a bit more convenient than what's possible with the `Value` API currently.

**Comment by emoon** [comment]
Great! I will try to take a look this week.

**Comment by rotty** [comment]
I've now merged the code that should satisfy this feature request; thanks for adding the proverbial drop in the bucket that lead me to implement it! If you perceive any deficiencies in the added code and documentation, please feel free to open new issues.
